// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq2UQuF2yNA0K9FbEKCZefKReR43jDE_w',
    appId: '1:1043163647450:web:928d16f027f59e63c804e3',
    messagingSenderId: '1043163647450',
    projectId: 'chatt-app-8eb40',
    authDomain: 'chatt-app-8eb40.firebaseapp.com',
    storageBucket: 'chatt-app-8eb40.appspot.com',
    measurementId: 'G-CT32BYMQ5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRnluYGdV0OQ31YQj5_jiDEDX-rnbEF0',
    appId: '1:1043163647450:android:69b75974afb6b5cac804e3',
    messagingSenderId: '1043163647450',
    projectId: 'chatt-app-8eb40',
    storageBucket: 'chatt-app-8eb40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmUmUlJRVTtU-wrQmmz5hQXu-pqfx2krI',
    appId: '1:1043163647450:ios:b4f86902c6661d1bc804e3',
    messagingSenderId: '1043163647450',
    projectId: 'chatt-app-8eb40',
    storageBucket: 'chatt-app-8eb40.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmUmUlJRVTtU-wrQmmz5hQXu-pqfx2krI',
    appId: '1:1043163647450:ios:b4f86902c6661d1bc804e3',
    messagingSenderId: '1043163647450',
    projectId: 'chatt-app-8eb40',
    storageBucket: 'chatt-app-8eb40.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq2UQuF2yNA0K9FbEKCZefKReR43jDE_w',
    appId: '1:1043163647450:web:8068ad50a718ca28c804e3',
    messagingSenderId: '1043163647450',
    projectId: 'chatt-app-8eb40',
    authDomain: 'chatt-app-8eb40.firebaseapp.com',
    storageBucket: 'chatt-app-8eb40.appspot.com',
    measurementId: 'G-01G07M0YWP',
  );
}
